http: 8222
jetstream: enabled
server_name: ecupl_edu_$POD_NAME
jetstream {
    store_dir: /data
    max_mem: 1G
    max_file: 10G
    domain: ecupl_edu
}
leafnodes {
    port: 7422
   
    remotes = [ 
        { 
          url: "nats://nats.helpwx.com?auth_token=sudy12344"
        },
    ]
   
}
lame_duck_grace_period: 10s
lame_duck_duration: 30s
##################
#                #
# Authorization  #
#                #
##################
authorization {
  token: "secret"
}