http_port: 8222
port: 4222
server_name: mpk

jetstream {
  store_dir: /data
  max_mem: 2G
  max_file: 15G
}


accounts {
  LEAF: {
    users:[],
    imports:[
      {service: {account: MONITOR, subject: "sudy.monitor.req.mpk.>"}},
      {stream: {account: MONITOR, subject: "sudy.monitor.notify.mpk.>"}},
      {stream: {account: CM, subject: "sudy.securityCenter.notify.mpk.>"}},
      {service: {account: CM, subject: "sudy.securityCenter.req.mpk.>"}},
      {stream: {account: CM, subject: "sudy.ai.notify.mpk.qalog"}},
      {stream: {account: CM, subject: "sudy.webplus.notify.mpk.*.yuyue.log"}},

    ],
    exports:[
      {service: "sudy.sms.req.fdyuan-fudan-local.fudanyuan.mobileVerify"},
      {service: "wx.>"},
      {service: "server.data.mpk.*"},
      {stream: "server.data.mpk.*"},
      {service: "sudy.newmedia.req.mpk.>"},
      {stream: "sudy.newmedia.notify.mpk.>"},
    ]
  },
  MONITOR:{
    users:[{nkey:UBCWL6PY2V4TWS6LZBLVW44TCCAHCBZZ3HKL4LFQV466QOJC46B7EKVM},{user:m,password:m}],
    exports: [
      {service: "sudy.monitor.req.mpk.>"},
      {stream: "sudy.monitor.notify.mpk.>"},
    ],
    #jetstream: enabled
  },
  CM:{
    users:[{nkey:UBUGBPDHPW44AA4I6YNUDJ4GFRSMNJFNMU64BMBJTQDXLLACII5CSXTP},{user:c,password:c}],
    exports:[
      {stream: "sudy.securityCenter.notify.mpk.>"},
      {stream: "sudy.ai.notify.mpk.>"},
      {stream: "sudy.webplus.notify.mpk.*.yuyue.log"},
      {service: "sudy.securityCenter.req.>"},
    ],
    imports:[
      {service: {account: LEAF, subject: "sudy.sms.req.fdyuan-fudan-local.fudanyuan.mobileVerify"}},
      {service: {account: LEAF, subject: "wx.>"}},
      {service: {account: LEAF, subject: "server.data.mpk.req"}},
      {service: {account: LEAF, subject: "server.data.mpk.reply"}},
      {stream: {account: LEAF, subject: "server.data.mpk.push"}},
      {service: {account: LEAF, subject: "sudy.newmedia.req.mpk.>"}},
      {stream: {account: LEAF, subject: "sudy.newmedia.notify.mpk.>"}},
    ],
    jetstream: enabled
  },
  AI:{
    users:[{nkey:UDLC45BBO7JJEAQLD3FPHUQG6S6NVAXBOUU3IXPMMOW7ID75JWR5WD4V}],
    jetstream: enabled
  },
  SYS:{
    users:[{nkey:UDZWTTETCAUUUPIHEZ6VVYBXS5346RXKNBPFOWXD64LB256J5XOECUUK}],
  }
}
system_account: SYS

lame_duck_grace_period: 10s
lame_duck_duration: 30s